### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by zealic** [zealic/verant#1]
`.verant.yml` config file.

## Rules
Match source line and specify version resolver, match sequence from define order

```yaml
version: "1"
# Override default rules
override: true
rules:
  - match: '^ENV\s+(?P<name>[A-Z_]+)_VER(\s+|=)(?P<version>[^#]+)'
    source: dockerfile
    resolver: docker
  - match: '^ENV\s+(?P<name>[A-Z_]+)_URL(\s+|=)(?P<url>[^#]+)'
    source: dockerfile
    resolver: web
  - match: '^ENV\s+(?P<name>[A-Z_]+)_URL(\s+|=)(?P<url>https:\/\/github.com[^#]+)'
    source: dockerfile
    resolver: github
  - match: '^ENV\s+(?P<name>[A-Z_]+)_REPO(\s+|=)(?P<url>https:\/\/github.com[^#]+)'
    source: dockerfile
    resolver: github
  - match: '^ENV\s+(?P<name>[A-Z_]+)_RESOLVER(\s+|=)(?P<resolver>[^#]+)'
    source: dockerfile
    # Resolver will be ignored, use custom resolver
    resolver: github
  - match: '^# verant: set-resolver\s+(?P<name>[A-Z_]+)\s+(?P<custom_resolver>[^#]+)'
    source: dockerfile
    # use custom resolver
    captures:
      # Map custom_resolver to resolver
      custom_resolver: resolver
```

## Includes & Excludes
Scan files with **Includes & Excludes** support.

```yaml
includes:
  # all Dockerfile
  - Dockerfile
  # all shell scripts in /scripts dir
  - /scripts/**/*.sh
excludes:
  - /vendor/**/Dockerfile # ignore Dockerfile in vendor directory
```

Use [xignore](https://github.com/zealic/xignore) implement `includes` and `excludes`.

### Reference
* [Regex for Golang online](https://regex-golang.appspot.com/assets/html/index.html)
